import type { SolutionContent } from './types';

const content: SolutionContent = {
  slug: 'data-platforms',
  heroLead:
    'Data engineering, platforms and governance built for critical industries — trusted pipelines, lakehouse foundations and self-service analytics that operations can actually rely on.',
  overview: [
    'Data & Platforms is where the data generated by critical operations becomes a dependable, governed asset. From trackside sensors and OCC systems to enterprise applications, we engineer the pipelines, platforms and controls that turn raw signals into trustworthy information.',
    'This is data engineering done with the same rigour we apply to safety- and mission-critical systems. We build resilient ingestion, lakehouse and warehouse foundations, and the governance and quality controls that make data fit to drive decisions, AI and regulatory reporting.',
    'Because we engineer the underlying platforms ourselves, analytics and AI sit on foundations we genuinely understand — lineage you can trace, quality you can measure and self-service access you can govern. That depth is what makes data usable across railways, energy, oil & gas and beyond.',
  ],
  stats: [
    { value: 'OT + IT', label: 'Unified data sources' },
    { value: 'Governed', label: 'Quality & lineage by design' },
    { value: 'Real-time', label: 'Streaming & batch pipelines' },
    { value: 'Self-service', label: 'Trusted access for teams' },
  ],
  services: [
    { n: '01', title: 'Data Engineering & Pipelines', desc: 'Resilient ingestion and transformation across streaming and batch sources.', points: ['Streaming & batch ingestion', 'OT/IT data integration', 'Transformation & modelling', 'Reliable, observable pipelines'] },
    { n: '02', title: 'Lakehouse & Warehouse Platforms', desc: 'Scalable lakehouse and warehouse foundations that operations run on.', points: ['Lakehouse architecture', 'Cloud data warehousing', 'Storage & compute optimisation', 'Performance & cost tuning'] },
    { n: '03', title: 'Data Governance & Quality', desc: 'Controls that make data trustworthy, traceable and compliant.', points: ['Data cataloguing & lineage', 'Quality rules & monitoring', 'Access control & security', 'Compliance & auditability'] },
    { n: '04', title: 'Self-Service Analytics', desc: 'Governed, curated access that puts trusted data in the hands of teams.', points: ['Curated semantic layers', 'BI & dashboarding enablement', 'Role-based governed access', 'Analytics readiness for AI'] },
  ],
  approach: [
    { step: '01', title: 'Model the domain', desc: 'We start from the operational data — its sources, meaning and the decisions it must support.' },
    { step: '02', title: 'Engineer the platform', desc: 'Resilient pipelines and a lakehouse or warehouse foundation, built observable from day one.' },
    { step: '03', title: 'Govern for trust', desc: 'We layer in cataloguing, lineage, quality and access controls so data stays fit for purpose.' },
    { step: '04', title: 'Enable & sustain', desc: 'We open governed self-service access and sustain the platform as data and demand grow.' },
  ],
  outcomes: [
    { title: 'Data you can trust', desc: 'Governed pipelines with measurable quality and traceable lineage you can stand behind.' },
    { title: 'A foundation for AI', desc: 'Clean, well-modelled data that makes analytics and AI credible rather than guesswork.' },
    { title: 'Faster, safer decisions', desc: 'Self-service access to trusted data lets teams act with confidence and accountability.' },
  ],
  tech: ['Apache Spark', 'Databricks & lakehouse', 'Cloud data warehousing', 'Apache Kafka', 'dbt', 'Apache Airflow', 'Data catalog & governance', 'Azure / AWS / GCP data services', 'Delta Lake / Iceberg', 'Python / SQL', 'BI & visualisation', 'CI/CD for data'],
  faqs: [
    { q: 'How is this different from a generic data project?', a: 'We engineer data platforms with the rigour critical systems demand — resilient pipelines, traceable lineage and governed quality, not just dashboards.' },
    { q: 'Can you unify OT and IT data?', a: 'Yes. We integrate operational sources such as sensors and control systems with enterprise applications into governed, usable platforms.' },
    { q: 'Do you handle governance and quality, not just pipelines?', a: 'Governance, cataloguing, lineage and quality monitoring are built in from the start so data stays trustworthy and auditable.' },
    { q: 'How does this support AI and analytics?', a: 'Clean, well-modelled, governed data is the foundation that makes analytics and AI credible — we build that foundation deliberately.' },
  ],
};

export default content;
